<?php
require_once __DIR__.'/config/db.php';
$pageTitle = 'Terms & Conditions';
$activeNav = '';
include __DIR__.'/includes/header.php';
?>
<main class="inner-page">
  <div class="container inner-hero">
    <div class="eyebrow">Legal <span></span></div>
    <h1>Terms &amp; Conditions</h1>
    <p>Last updated: September 2026</p>
  </div>
  <div class="container content-narrow" style="padding-bottom:80px">
    <div class="prose">
      <p>By using the Karn High School website, online application portal, or any portal provided by the school management information system, you agree to the following terms.</p>
      <h3 style="font-size:18px;font-weight:700;margin:24px 0 10px">Acceptable Use</h3>
      <p>Users must use the system only for lawful purposes related to school administration, admissions and academic management. Unauthorised access, sharing of login credentials, or misuse of the system is strictly prohibited.</p>
      <h3 style="font-size:18px;font-weight:700;margin:24px 0 10px">Application Accuracy</h3>
      <p>All information submitted in an online application must be truthful and accurate. Karn High School reserves the right to reject or withdraw an admission offer if false information is discovered at any stage.</p>
      <h3 style="font-size:18px;font-weight:700;margin:24px 0 10px">Entrance Examination</h3>
      <p>Applicants who take the online entrance examination must do so independently. Any form of cheating or assistance from others is grounds for disqualification. The school reserves the right to verify results through additional assessment.</p>
      <h3 style="font-size:18px;font-weight:700;margin:24px 0 10px">Payments</h3>
      <p>School fees, once paid, are subject to the school's refund policy. Receipts generated by the system serve as proof of payment. Please contact the bursar office for any payment disputes.</p>
      <h3 style="font-size:18px;font-weight:700;margin:24px 0 10px">Intellectual Property</h3>
      <p>All content on the Karn High School website and management system, including text, images, logos and documents, is the property of Karn High School and may not be reproduced without written permission.</p>
      <h3 style="font-size:18px;font-weight:700;margin:24px 0 10px">Changes</h3>
      <p>Karn High School reserves the right to update these terms at any time. Continued use of the system constitutes acceptance of any revised terms.</p>
    </div>
  </div>
</main>
<?php include __DIR__.'/includes/footer.php'; ?>
