<?php
$pageTitle   = 'Backup & Restore';
$activeAdmin = 'backup';
require_once dirname(__DIR__).'/includes/admin_header.php';
requireRole(['sys_admin','super_admin']);

$pdo     = db();
$backupDir = BASE_PATH . '/backups';
if (!is_dir($backupDir)) { mkdir($backupDir, 0755, true); }

$tab = $_GET['tab'] ?? 'backup';
$msg = ''; $msgType = 'ok';

// ── POST actions ──────────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verifyCsrf();
    $action = $_POST['action'] ?? '';

    if ($action === 'create_backup') {
        // Generate SQL dump using mysqldump if available, else PHP fallback
        $dbName  = 'karnhighschool';
        $stamp   = date('Y-m-d_H-i-s');
        $label   = preg_replace('/[^a-z0-9_\-]/i','_',trim($_POST['label']??'manual'));
        $outFile = $backupDir . "/backup_{$label}_{$stamp}.sql";

        $mysqldump = 'C:\\xampp\\mysql\\bin\\mysqldump.exe';
        if (file_exists($mysqldump)) {
            $cmd = "\"$mysqldump\" -u root --no-tablespaces $dbName > \"$outFile\" 2>&1";
            exec($cmd, $output, $code);
            if ($code === 0 && file_exists($outFile) && filesize($outFile) > 0) {
                $size = filesize($outFile);
                // Log backup
                try {
                    $pdo->prepare("INSERT INTO backup_history (filename,size_bytes,created_by,label) VALUES (?,?,?,?)")
                       ->execute([basename($outFile), $size, currentUser()['name'], $label]);
                } catch (Throwable $e) { /* table may not exist yet */ }
                auditLog('create','backup','database',0,'',basename($outFile));
                flash('success','Backup created: '.basename($outFile).' ('.round($size/1024,1).' KB)');
            } else {
                flash('error','Backup failed. Check server permissions or run mysqldump manually.');
            }
        } else {
            // PHP-level table-data export fallback
            try {
                $tables = $pdo->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);
                $sql = "-- KHSMIS Backup: $stamp\n-- Generated by PHP fallback\nSET FOREIGN_KEY_CHECKS=0;\n\n";
                foreach ($tables as $table) {
                    $sql .= "DROP TABLE IF EXISTS `$table`;\n";
                    $create = $pdo->query("SHOW CREATE TABLE `$table`")->fetch();
                    $sql .= $create[1].";\n\n";
                    $rows = $pdo->query("SELECT * FROM `$table`")->fetchAll(PDO::FETCH_ASSOC);
                    foreach ($rows as $row) {
                        $vals = array_map(fn($v) => $v===null?'NULL':"'".$pdo->quote(trim($v??''))."'", $row);
                        $sql .= "INSERT INTO `$table` VALUES (".implode(',', $vals).");\n";
                    }
                    $sql .= "\n";
                }
                $sql .= "SET FOREIGN_KEY_CHECKS=1;\n";
                file_put_contents($outFile, $sql);
                $size = strlen($sql);
                auditLog('create','backup','database',0,'',basename($outFile).' (PHP fallback)');
                flash('success','Backup created (PHP fallback): '.basename($outFile));
            } catch (Throwable $e) {
                flash('error','Backup failed: '.$e->getMessage());
            }
        }
        redirect(BASE_URL.'/admin/backup.php?tab=history');
    }

    elseif ($action === 'delete_backup') {
        $file = basename($_POST['file'] ?? '');
        $path = $backupDir.'/'.$file;
        if ($file && file_exists($path) && str_ends_with($file, '.sql')) {
            unlink($path);
            try { $pdo->prepare("DELETE FROM backup_history WHERE filename=?")->execute([$file]); } catch (Throwable $e) {}
            auditLog('delete','backup','file',0,'',$file);
            flash('success','Backup deleted: '.$file);
        }
        redirect(BASE_URL.'/admin/backup.php?tab=history');
    }

    elseif ($action === 'export_csv') {
        // Quick full-data CSV export for a specific table
        $table = preg_replace('/[^a-z0-9_]/i','', $_POST['table']??'');
        if ($table) {
            try {
                $rows = $pdo->query("SELECT * FROM `$table` LIMIT 10000")->fetchAll(PDO::FETCH_ASSOC);
                header('Content-Type: text/csv');
                header('Content-Disposition: attachment; filename="'.$table.'_'.date('Y-m-d').'.csv"');
                $fp = fopen('php://output','w');
                if (!empty($rows)) {
                    fputcsv($fp, array_keys($rows[0]));
                    foreach ($rows as $r) fputcsv($fp, $r);
                }
                fclose($fp); exit;
            } catch (Throwable $e) {
                flash('error','Export failed: '.$e->getMessage());
            }
        }
        redirect(BASE_URL.'/admin/backup.php?tab=export');
    }
    redirect(BASE_URL.'/admin/backup.php?tab='.urlencode($tab));
}

// ── Load backup history ───────────────────────────────────────
// From files on disk
$backupFiles = [];
foreach (glob($backupDir.'/*.sql') as $f) {
    $backupFiles[] = [
        'filename' => basename($f),
        'size'     => filesize($f),
        'modified' => filemtime($f),
    ];
}
usort($backupFiles, fn($a,$b) => $b['modified'] <=> $a['modified']);

// DB tables for export
$dbTables = $pdo->query("SELECT table_name,table_rows,data_length+index_length size FROM information_schema.tables WHERE table_schema='karnhighschool' ORDER BY table_name")->fetchAll();

// Stats
$totalBackups = count($backupFiles);
$totalSize    = array_sum(array_column($backupFiles,'size'));
$lastBackup   = $totalBackups > 0 ? $backupFiles[0]['modified'] : null;
?>

<div class="page-heading">
  <div>
    <div class="eyebrow">System <span></span></div>
    <h1>Backup &amp; Restore</h1>
    <p>Database backups, data exports and restore operations.</p>
  </div>
</div>

<!-- Metrics -->
<div class="metric-grid" style="margin-bottom:24px">
  <div class="metric-card">
    <div class="metric-top"><span>Total Backups</span><div class="metric-icon">💾</div></div>
    <strong><?= $totalBackups ?></strong>
    <small><i></i>Stored locally</small>
  </div>
  <div class="metric-card">
    <div class="metric-top"><span>Storage Used</span><div class="metric-icon">📁</div></div>
    <strong><?= $totalSize > 0 ? round($totalSize/1024/1024,2).' MB' : '0 MB' ?></strong>
    <small><i></i>Backup files</small>
  </div>
  <div class="metric-card">
    <div class="metric-top"><span>Last Backup</span><div class="metric-icon">🕐</div></div>
    <strong style="font-size:14px"><?= $lastBackup ? date('M d, Y H:i', $lastBackup) : 'Never' ?></strong>
    <small><i></i><?= $lastBackup ? date('l', $lastBackup) : 'No backups yet' ?></small>
  </div>
  <div class="metric-card">
    <div class="metric-top"><span>DB Tables</span><div class="metric-icon">🗄️</div></div>
    <strong><?= count($dbTables) ?></strong>
    <small><i></i>karnhighschool database</small>
  </div>
</div>

<!-- Tabs -->
<div class="tab-bar" style="margin-bottom:16px">
  <a href="?tab=backup"  class="tab-btn <?= $tab==='backup' ?'active':'' ?>">💾 Create Backup</a>
  <a href="?tab=history" class="tab-btn <?= $tab==='history'?'active':'' ?>">📋 Backup History (<?= $totalBackups ?>)</a>
  <a href="?tab=export"  class="tab-btn <?= $tab==='export' ?'active':'' ?>">📥 Data Export</a>
</div>

<?php if ($tab === 'backup'): ?>
<!-- ── CREATE BACKUP ─────────────────────────────────────── -->
<div class="panel" style="padding:28px;max-width:560px">
  <h3 style="font-weight:700;margin-bottom:6px">💾 Create Database Backup</h3>
  <p style="font-size:13px;color:var(--ink-soft);margin-bottom:20px">
    Creates a full SQL dump of the <strong>karnhighschool</strong> database.
    Backups are stored in the <code>/backups/</code> folder on the server.
  </p>
  <form method="post">
    <?= csrfField() ?>
    <input type="hidden" name="action" value="create_backup"/>
    <div class="form-group" style="margin-bottom:16px">
      <label style="font-size:13px;font-weight:600;display:block;margin-bottom:6px">Backup Label (optional)</label>
      <input type="text" name="label" placeholder="e.g. before_upgrade, end_of_term"
             style="width:100%;padding:10px;border:1.5px solid var(--line);border-radius:var(--radius-sm);font-size:14px;font-family:inherit"
             pattern="[a-zA-Z0-9_\-]+" title="Letters, numbers, hyphens and underscores only"/>
    </div>
    <button type="submit" class="button button-primary">💾 Create Backup Now</button>
  </form>

  <div style="margin-top:24px;padding:16px;background:var(--bg);border-radius:var(--radius-sm)">
    <strong style="font-size:13px">⚠️ Important Notes</strong>
    <ul style="margin:8px 0 0 16px;font-size:12.5px;color:var(--ink-soft);display:flex;flex-direction:column;gap:4px">
      <li>Backup files are stored on this server only — download them for off-site safety.</li>
      <li>Schedule regular backups before major system changes.</li>
      <li>Only System Administrators can create or delete backups.</li>
      <li>Restoring a backup will overwrite all current data.</li>
    </ul>
  </div>
</div>

<?php elseif ($tab === 'history'): ?>
<!-- ── BACKUP HISTORY ────────────────────────────────────── -->
<?php if (empty($backupFiles)): ?>
<div style="text-align:center;padding:48px;background:var(--surface);border:1px solid var(--line);border-radius:var(--radius)">
  <div style="font-size:40px;margin-bottom:12px">💾</div>
  <h3 style="margin-bottom:6px">No backups yet</h3>
  <p style="color:var(--ink-soft)">Create your first backup using the Create Backup tab.</p>
  <a href="?tab=backup" class="button button-primary" style="margin-top:16px">Create Backup</a>
</div>
<?php else: ?>
<div class="table-wrap">
  <table>
    <thead><tr><th>Filename</th><th>Size</th><th>Created</th><th>Actions</th></tr></thead>
    <tbody>
      <?php foreach ($backupFiles as $bf): ?>
      <tr>
        <td>
          <strong style="font-size:13px"><?= e($bf['filename']) ?></strong>
        </td>
        <td class="muted"><?= round($bf['size']/1024, 1) ?> KB</td>
        <td class="muted"><?= date('M d, Y H:i', $bf['modified']) ?></td>
        <td>
          <div style="display:flex;gap:6px">
            <a href="<?= BASE_URL ?>/backups/index.php?file=<?= urlencode($bf['filename']) ?>"
               class="filter-button button-sm" download>📥 Download</a>
            <form method="post" onsubmit="return confirm('Delete this backup?')" style="display:inline">
              <?= csrfField() ?>
              <input type="hidden" name="action" value="delete_backup"/>
              <input type="hidden" name="file"   value="<?= e($bf['filename']) ?>"/>
              <input type="hidden" name="tab"    value="history"/>
              <button type="submit" class="filter-button button-sm" style="color:var(--error)">🗑️ Delete</button>
            </form>
          </div>
        </td>
      </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>
<?php endif; ?>

<?php elseif ($tab === 'export'): ?>
<!-- ── DATA EXPORT ───────────────────────────────────────── -->
<div class="panel" style="padding:24px;margin-bottom:20px">
  <h3 style="font-weight:700;margin-bottom:6px">📥 Export Table Data (CSV)</h3>
  <p style="font-size:13px;color:var(--ink-soft);margin-bottom:16px">Export any database table as a CSV file. Limited to 10,000 rows per export.</p>
  <form method="post" style="display:flex;gap:10px;flex-wrap:wrap;align-items:flex-end">
    <?= csrfField() ?>
    <input type="hidden" name="action" value="export_csv"/>
    <div>
      <label style="font-size:12px;font-weight:600;display:block;margin-bottom:4px">Select Table</label>
      <select name="table" style="padding:9px 12px;border:1.5px solid var(--line);border-radius:var(--radius-sm);font-size:13px;font-family:inherit;min-width:200px">
        <?php foreach ($dbTables as $t): ?>
        <option value="<?= e($t['table_name']) ?>"><?= e($t['table_name']) ?> (~<?= number_format((int)$t['table_rows']) ?> rows)</option>
        <?php endforeach; ?>
      </select>
    </div>
    <button type="submit" class="button button-secondary">📥 Export CSV</button>
  </form>
</div>

<div class="table-wrap">
  <table>
    <thead><tr><th>Table Name</th><th>Est. Rows</th><th>Size</th><th>Export</th></tr></thead>
    <tbody>
      <?php foreach ($dbTables as $t): ?>
      <tr>
        <td><strong><?= e($t['table_name']) ?></strong></td>
        <td class="muted"><?= number_format((int)$t['table_rows']) ?></td>
        <td class="muted"><?= round(($t['size']??0)/1024, 1) ?> KB</td>
        <td>
          <form method="post" style="display:inline">
            <?= csrfField() ?>
            <input type="hidden" name="action" value="export_csv"/>
            <input type="hidden" name="table"  value="<?= e($t['table_name']) ?>"/>
            <button type="submit" class="filter-button button-sm">📥 CSV</button>
          </form>
        </td>
      </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>
<?php endif; ?>

<?php require_once dirname(__DIR__).'/includes/admin_footer.php'; ?>
