/*
# Create KARN HIGH SCHOOL admissions foundation

1. New Tables
- `applications` stores online admission applications for the single school.
- Applicant identity, contact, education, requested grade, academic year, workflow status, and secure reference fields are included.

2. Security
- Row level security is enabled.
- Unauthenticated visitors may submit an application, but cannot read or modify applications.
- Authenticated staff can review and manage all applications for the school.

3. Important Notes
- This is intentionally single-school data for KARN HIGH SCHOOL.
- Application numbers are generated by the application layer and should not be treated as secrets.
*/

CREATE TABLE IF NOT EXISTS public.applications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  application_number text NOT NULL UNIQUE,
  first_name text NOT NULL,
  middle_name text,
  last_name text NOT NULL,
  date_of_birth date NOT NULL,
  gender text NOT NULL,
  nationality text NOT NULL DEFAULT 'Liberian',
  phone text NOT NULL,
  email text,
  current_address text NOT NULL,
  community text,
  county text NOT NULL DEFAULT 'Nimba',
  district text,
  previous_school text,
  last_grade_completed text,
  grade_applying_for text NOT NULL,
  academic_year text NOT NULL,
  guardian_name text NOT NULL,
  guardian_relationship text NOT NULL,
  guardian_phone text NOT NULL,
  emergency_contact text,
  status text NOT NULL DEFAULT 'Application Submitted',
  document_status text NOT NULL DEFAULT 'Pending',
  entrance_status text NOT NULL DEFAULT 'Not scheduled',
  final_decision text NOT NULL DEFAULT 'Pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can submit applications" ON public.applications;
CREATE POLICY "Public can submit applications" ON public.applications
  FOR INSERT TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Staff can view applications" ON public.applications;
CREATE POLICY "Staff can view applications" ON public.applications
  FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Staff can update applications" ON public.applications;
CREATE POLICY "Staff can update applications" ON public.applications
  FOR UPDATE TO authenticated
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Staff can delete applications" ON public.applications;
CREATE POLICY "Staff can delete applications" ON public.applications
  FOR DELETE TO authenticated
  USING (true);

CREATE INDEX IF NOT EXISTS applications_status_idx ON public.applications(status);
CREATE INDEX IF NOT EXISTS applications_grade_idx ON public.applications(grade_applying_for);
CREATE INDEX IF NOT EXISTS applications_phone_idx ON public.applications(phone);
